/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.SallyStashGame;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello world!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!";
    }

    public static void main(String[] args) {
      Scanner sc = new Scanner(System.in);
      Game g = new Game(sc);
      g.run(sc);
    }
}
