/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package server;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import shared.*;
/*
class ServerTest {
    @Test void testhandler() {
        ArrayList<Territory> map = new ArrayList<Territory>();
        Map<Integer, ArrayList<Operation> > actions = new HashMap<Integer, ArrayList<Operation> >();
        map.add(new Territory(0, 0, "Test Territory"));
        map.get(0).setDefenderNum(10);
    }
}
*/
