# services:
#   - postgres:latest
  
# variables:
#     POSTGRES_DB: risc
#     POSTGRES_USER: postgres
#     POSTGRES_PASSWORD: abc123
#     POSTGRES_HOST_AUTH_METHOD: trust
#     POSTGRES_HOST: postgres
#     POSTGRES_PORT: 5432

before_script:
  - hostname
  - whoami
  - pwd
  - ls -la
  - docker --version
  - docker-compose --version

stages:
   - build
   - test
   - coverage
   - deploy
   - test-deployment

   
build:
  tags:
     - ece651
  stage: build
  script: docker build --build-arg LOCAL_USER_ID=`id -u`  --tag citest .

test:
  tags:
     - ece651
  stage: test
  script: scripts/run-tests-in-docker.sh
  artifacts:
    paths:
      - coverage

pages:
 stage: coverage
 tags:
     - ece651
 dependencies:
   - test
 script:
   - mv coverage public/
 artifacts:
   paths:
     - public
      
deploy:
  tags: 
     - ece651 
  stage: deploy
  script: ./scripts/redeploy.sh
    #  - docker-compose stop
    #  - docker-compose up --build
 
test-deployment: 
  tags: 
     - ece651 
  stage: test-deployment 
  dependencies: 
     - deploy 
  script: ./scripts/test-deployment.sh
 
